{% set name = "pnpm" %}
{% set version = "9.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 50aff23584224ba237524a3ee2772896c7b7bb101569006483b5d97f6ca758b5

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - make
    - nodejs
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - pnpm --help

about:
  home: https://github.com/pnpm/pnpm
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: 📦🚀 Fast, disk space efficient package manager

extra:
  recipe-maintainers:
    - xhochy
    - pavelzw
    - JannikWibkerQC
